### PR TITLE
fix: inputs nav overflow

### PR DESCRIPTION
**Pull request by JoeBello**
Before:

before

After:

after

### CODE REVIEW

**Comment by tehpsalmist** [comment]
What happens if you resize the window smaller?

**Comment by JoeBello** [comment]
In the process of getting a couple images together I found a small window (1530px wide - 1540px wide) where the tabs got a bit awkward; changing the max-width from 95% to 90% fixed this.

1000px wide



525px wide

**Comment by tehpsalmist** [comment]
and that still looks good at the larger/largest widths? I'm just pushing back a little because 90% or 95% just seems like a magic number.

**Comment by JoeBello** [comment]
I understand your point, but at the same time I don't think 90% or 95% are magical; I'm essentially saying I only want to allot a percentage of the space for the navigation. I think 93px or even 93% could qualify as having magical properties.

2000 px with the max-width change 
2000 on

2000 px without the max-width change
2000 off

3000 px with the max-width change
3000 on

3000 px without the max-width change
3000 off

Alternatively, we could override the 8px right margin I think Bootstrap is applying
css

and instead add margin around the button container using ems (because ems are used for most of the padding/margins of the section container)

addition

but the result is not as clean around 1200px - 1350px
alt

**Comment by tehpsalmist** [comment]
Rock on

**Pull request merged**
